- name: Configure standard alarm definitions
  hosts: monasca_master
  gather_facts: no
  roles:
    - {role: monasca-default-alarms,
       keystone_user: "{{ keystone_project_admin }}",
       keystone_password: "{{ keystone_project_admin_password }}",
       tags: [alarms]}
