- name: Configure standard alarm definitions
  hosts: monasca_master
  gather_facts: no
  tasks:
    - name: Setup root email notification method
      monasca_notification_method:
        name: "Email Root"
        type: 'EMAIL'
        address: 'root@localhost'
        keystone_url: "{{keystone_url}}"
        keystone_user: "{{keystone_project_admin}}"
        keystone_password: "{{keystone_project_admin_password}}"
      tags:
        - alarms
        - system_alarms
        - monasca_alarms
      register: out
    - name: Create System Alarm Definitions
      monasca_alarm_definition:
        name: "{{item.name}}"
        expression: "{{item.expression}}"
        keystone_token: "{{out.keystone_token}}"
        monasca_api_url: "{{out.monasca_api_url}}"
        alarm_actions:
          - "{{out.notification_method_id}}"
        ok_actions:
          - "{{out.notification_method_id}}"
        undetermined_actions:
          - "{{out.notification_method_id}}"
      with_items:
        - { name: "Host Alive Alarm", expression: "host_alive_status > 0" }
        - { name: "High CPU usage", expression: "avg(cpu.idle_perc) < 10 times 3" }
        - { name: "Disk Inode Usage", expression: "disk.inode_used_perc > 90" }
        - { name: "Disk Usage", expression: "disk.space_used_perc > 90" }
        - { name: "Memory usage", expression: "avg(mem.usable_perc) < 10 times 3" }
        - { name: "Network Errors", expression: "net.in_errors >5 or net.out_errors > 5" }
      tags:
        - alarms
        - system_alarms
    - name: Create Monasca Alarm Definitions
      monasca_alarm_definition:
        name: "{{item.name}}"
        expression: "{{item.expression}}"
        keystone_token: "{{out.keystone_token}}"
        monasca_api_url: "{{out.monasca_api_url}}"
        alarm_actions:
          - "{{out.notification_method_id}}"
        ok_actions:
          - "{{out.notification_method_id}}"
        undetermined_actions:
          - "{{out.notification_method_id}}"
      with_items:
        - { name: "Monasca Agent emit time", expression: "avg(monasca.emit_time_sec) > 2 times 3" }
        - { name: "Monasca Agent collection time", expression: "avg(monasca.collection_time_sec) > 5 times 3" }
        - { name: "Monasca Configuration DB query time", expression: "avg(monasca.config_db_time.95percentile) > 5 times 3" }
        - { name: "Zookeeper Average Latency", expression: "avg(zookeeper.avg_latency_sec) > 1 times 3" }
      tags:
        - alarms
        - monasca_alarms
