- name: Configures the Mysql schema and users
  hosts: mysql_host
  sudo: yes
  roles:
    - {role: monasca-schema, influxdb_schema_enabled: false, kafka_topics_enabled: false, mysql_schema_enabled: true, tags: [schema]}
