- hosts: monasca
  sudo: yes
  tasks:
    - name: apt-get update
      apt: update_cache=yes

- include: monasca_deps.yml
- include: schema.yml
- include: monasca.yml
- include: agent.yml
- include: alarms.yml
- include: agent_status.yml
