- hosts: monasca
  sudo: yes
  tasks:
    - name: Check for database_type
      fail: msg="Must set database type when running this playbook. To pass via command line use -e."
      when: database_type is not defined
    - name: apt-get update
      apt: update_cache=yes

- include: monasca_deps.yml
- include: mysql_schema.yml
- include: schema.yml
- include: monasca.yml
- include: agent.yml
- include: alarms.yml
- include: agent_status.yml
